"""Constantes y roles compartidos por el canvas."""

DEFAULT_PAPER_WIDTH = 800
DEFAULT_PAPER_HEIGHT = 1000
PAPER_MARGIN = 40
ATOM_HIT_RADIUS = 16.0
DEFAULT_BOND_LENGTH = 40.0
HOVER_ATOM_RADIUS = 16.0
HOVER_BOND_DISTANCE = 10.0
OPTIMIZE_ZONE_SCALE = 1.2
CHAIN_MAX_BONDS = 120
BRANCH_ROTATION_STEP_DEG = 60.0
BRANCH_ROTATION_NOOP_TOLERANCE_DEG = 0.15
FRAGMENT_ROTATION_STEP_DEG = 30.0
CLIPBOARD_RENDER_SCALE = 5.0
CLIPBOARD_LARGE_SELECTION_RENDER_SCALE = 2.5
CLIPBOARD_LARGE_SELECTION_ATOM_THRESHOLD = 18
CLIPBOARD_LARGE_SELECTION_BOND_THRESHOLD = 20
PASTE_IMAGE_OFFSET_PX = 20.0
PASTE_IMAGE_MAX_PAPER_FRACTION = 0.72
TRACKBALL_ROTATION_DEG_PER_PIXEL = 1.0
TRACKBALL_MAX_TILT_DEG = 60.0
TRACKBALL_REFERENCE_MATCH_TOLERANCE_PX = 1.5
ANGLE_OCCUPIED_TOLERANCE_DEG = 20.0
SP3_OCCUPIED_TOLERANCE_DEG = 8.0
MIN_ATOM_DIST_SCALE = 0.65
MIN_BOND_DIST_SCALE = 0.2
COLLISION_LENGTH_BOOST = 1.2
BOND_OVERLAP_TOLERANCE_PX = 5.0
BOND_DRAG_THRESHOLD_PX = 6.0
BOND_LAST_ANGLE_TOLERANCE_DEG = 20.0
LABEL_OFFSET_SCALE = 0.6
LABEL_OFFSET_MIN_PX = 4.0
RULER_THICKNESS_PX = 24
RULER_MAJOR_STEP_PX = 100
RULER_MINOR_STEP_PX = 20
GRID_MINOR_STEP_PX = 20
GRID_MAJOR_STEP_PX = 100
SELECTION_BOX_PADDING_PX = 6.0
SELECTION_HANDLE_RADIUS_PX = 6.0
SELECTION_HANDLE_OFFSET_PX = 18.0
SELECTION_ROTATE_OFFSET_PX = 13.0
SELECTION_MOVE_OFFSET_PX = 0.0
ELECTRON_SLOT_TOLERANCE_DEG = 18.0
ELECTRON_PAIR_SPREAD_PX = 6.5

ELECTRON_DOT_ROLE = 1001
ELECTRON_ANCHOR_ROLE = 1002
ELECTRON_SLOT_ROLE = 1003
ELECTRON_SIDE_ROLE = 1004
ELECTRON_SCALE_ROLE = 1005
WAVY_ANCHOR_ROLE = 2001
WAVY_ANCHOR_ANGLE_ROLE = 2002
WAVY_ANCHOR_LENGTH_ROLE = 2003
WAVY_ANCHOR_BOND_ROLE = 2004
AROMATIC_CIRCLE_ATOMS_ROLE = 3001
NUMBERING_TEXT_ROLE = 4001
NUMBERING_KIND_ROLE = 4002
NUMBERING_KEY_ROLE = 4003
NUMBERING_AUTO_TEXT_ROLE = 4004
IMPLICIT_H_OVERLAY_ANCHOR_ROLE = 5001
IMPLICIT_H_OVERLAY_ANGLE_ROLE = 5002
ITEM_OPACITY_ROLE = 5003
PAPER_ITEM_ROLE = 7001
ITEM_OPACITY_UNSET = object()

SUPPORTED_IMAGE_FILE_MIME_TYPES = {
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".svg": "image/svg+xml",
}
