"""Servicios de limpieza 2D desacoplados de la GUI."""

from .v2 import Clean2DParameters, optimize_clean2d_positions
from .safety import (
    Clean2DQualityReport,
    evaluate_clean2d_layout,
    is_clean2d_candidate_safe,
    has_cycles,
    count_new_bond_crossings,
    min_nonbonded_distance,
    ring_degeneracy_score,
    max_atom_displacement,
    bond_length_stats,
)
from .length_only import (
    length_only_polish,
    structure_preserving_geometry_polish,
    structure_preserving_length_polish,
)
from .complex_policy import Clean2DComplexityProfile, classify_clean2d_complexity
from .local_graph_cleaner import (
    LocalClean2DMode,
    LocalClean2DReport,
    LocalClean2DResult,
    LocalDefect,
    LocalRepair,
    RepairValidation,
    is_complex_clean2d_graph,
    local_graph_clean2d,
    stereo_layout_signature,
    validate_local_repair,
)
from .engine import (
    Clean2DMode,
    Clean2DCandidate,
    Clean2DResult,
    Clean2DInvariantError,
    Clean2DGraphSnapshot,
    Clean2DLayoutQualityReport,
    assert_clean2d_invariants,
    canonicalization_delta,
    capture_clean2d_snapshot,
    classify_clean2d_layout_quality,
    clean2d_geometry_hash,
    generate_clean2d_candidates,
    has_hierarchical_block_layout_signals,
    has_intramolecular_block_layout_problem,
    rank_clean2d_candidates,
    run_clean2d_engine,
    stable_clean2d_rejection_reason,
    STABLE_CLEAN2D_REJECTION_REASONS,
    summarize_clean2d_candidates,
)

__all__ = [
    "Clean2DParameters",
    "optimize_clean2d_positions",
    "Clean2DQualityReport",
    "evaluate_clean2d_layout",
    "is_clean2d_candidate_safe",
    "has_cycles",
    "count_new_bond_crossings",
    "min_nonbonded_distance",
    "ring_degeneracy_score",
    "max_atom_displacement",
    "bond_length_stats",
    "length_only_polish",
    "structure_preserving_geometry_polish",
    "structure_preserving_length_polish",
    "Clean2DComplexityProfile",
    "classify_clean2d_complexity",
    "LocalClean2DMode",
    "LocalClean2DReport",
    "LocalClean2DResult",
    "LocalDefect",
    "LocalRepair",
    "RepairValidation",
    "is_complex_clean2d_graph",
    "local_graph_clean2d",
    "stereo_layout_signature",
    "validate_local_repair",
    "Clean2DMode",
    "Clean2DCandidate",
    "Clean2DResult",
    "Clean2DInvariantError",
    "Clean2DGraphSnapshot",
    "Clean2DLayoutQualityReport",
    "assert_clean2d_invariants",
    "canonicalization_delta",
    "capture_clean2d_snapshot",
    "classify_clean2d_layout_quality",
    "clean2d_geometry_hash",
    "generate_clean2d_candidates",
    "has_hierarchical_block_layout_signals",
    "has_intramolecular_block_layout_problem",
    "rank_clean2d_candidates",
    "run_clean2d_engine",
    "stable_clean2d_rejection_reason",
    "STABLE_CLEAN2D_REJECTION_REASONS",
    "summarize_clean2d_candidates",
]
